### ISSUE TITLE
Create new certificate: missing content area

### ISSUE THREAD

**Issue by hoanglinhlan** [Kademi/kademi-dev#2868]
http://localhost:8080/certificates/cert_1/?useHash=true
![image](https://cloud.githubusercontent.com/assets/20508726/22918224/d674529e-f2bb-11e6-8070-4d7221945a27.png)

#2867

**Comment by ducdhm** [comment]
Fixed

**Comment by hoanglinhlan** [comment]
1: Chrome: Cant copy paste from word or other web ( use keyboard ). If I use paste item in editor, the system showing popup to paste the text that you want to copy but after click OK, the text is still not copy 
![image](https://cloud.githubusercontent.com/assets/20508726/22968097/ac42d7da-f39b-11e6-80a0-3a4752c2b246.png)


2: the text graph not full width 
![image](https://cloud.githubusercontent.com/assets/20508726/22967950/1e6e8c88-f39b-11e6-95a8-9be876871743.png)

**Comment by ducdhm** [comment]
@hoanglinhlan 
1. Please recheck. It works normally in my side
2. It's not full-width because it's certification. We fixed width for it!

**Comment by hoanglinhlan** [comment]
confirm passed
