### ISSUE TITLE
Integrate admin omnisearch with new omnisearch framework

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#3508]
Related https://github.com/Kademi/kademi-dev/issues/3416

**Comment by ducdhm** [comment]
Done!

**Comment by bradmac** [comment]
Integrated AdminApp to provide profile and org search results. LeadManApp is now disabled for admin context

**Comment by bradmac** [comment]
@AlaaKhalaf94 this is referring to the search at the top of the admin:

![image](https://user-images.githubusercontent.com/826458/28357492-b4ae1478-6cbf-11e7-9da2-335f8628daa3.png)

This should be the same as before, it should search for profiles and orgs. We've just changed the backend framework.

**Comment by AlaaKhalaf94** [comment]
Hi @Brad , I test it , and the search at the top of the admin still does not able to search for profiles and orgs as before

**Comment by ducdhm** [comment]
@AlaaKhalaf94 Can you reindex and re-test again?

**Comment by AlaaKhalaf94** [comment]
@ducdhm I have  reindex to all Indexes , and It does not work with me .

**Comment by AlaaKhalaf94** [comment]
passed
