### ISSUE TITLE
Org selector component issue

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4092]
Not filtering in front end

When typing in an ORG name, the only search that pulls up any org is typing the letter T

![image](https://user-images.githubusercontent.com/1945230/31269621-dc5f16ea-aa89-11e7-85ae-2f0f36f34c87.png)
![image](https://user-images.githubusercontent.com/1945230/31269635-e3b79610-aa89-11e7-80db-e59c146b782d.png)
T works for search because T symbol are in ORG id e.g. T1, t2 and so on, so probably search does not work by Organisation name.
If you type Califo.... it does not work.
https://github.com/Kademi/kademi-dev/issues/4087

**Comment by bradmac** [comment]
The problem is actually case-sensitivity.

I renamed "California" to "california" and now its appearing in search results.

**Comment by bradmac** [comment]
I've added orgTitle (indexed as text field) as well as title (indexed as keyword field), which should resolve the problem

**Comment by Uafinder** [comment]
Looks the same...
![image](https://user-images.githubusercontent.com/1945230/31327750-d3c5a89e-acd9-11e7-89e7-eeb54f37e84e.png)
![image](https://user-images.githubusercontent.com/1945230/31327757-db656e4a-acd9-11e7-90c4-e65822906378.png)
![image](https://user-images.githubusercontent.com/1945230/31327762-e91c7088-acd9-11e7-981e-ee504af9cc47.png)

http://moblix-reporting.kademi-ci.co/dashboard?miltonUserUrl=/users/report-user/&miltonUserUrlHash=635ce303-2681-41df-98e5-ae5c74e2ea06:_oMdiUeUlRG8_a3zvi11w53eXPY

http://version1.moblix-reporting.kademi-ci.co/contenteditor?fileName=points.html&miltonUserUrl=/users/patrick&miltonUserUrlHash=389f9d66-d2b2-4d7e-b396-43e78eab0643:caMwS5zeVdc5Jcoye4g3fOjUYHc

http://moblix.admin.kademi-ci.co/

**Comment by bradmac** [comment]
@tuzzmaniandevil can you look into this please?

**Comment by Uafinder** [comment]
1. I've cleared cache and created a fresh account:
http://vlad-test12.admin.kademi-ci.co/websites/
2. Create a website, add 4 orgs (exported from moblix)
3. Activate reporting lib
4. Create a fresh page and add there organisation selector component.
5. Still the same
6. http://vlad12-dash.kademi-ci.co/page1.html

So, when you try to select "california" it's ok, no matter what case you're using.
When you try to find for example New York, it finds nothing, no matter what case you're using.

**Comment by bradmac** [comment]
Hey @tuzzmaniandevil there's nothing in that commit to change the search logic, so i would be very surprised if that fixed anything!

Please ensure you confirm the fix works.

**Comment by tuzzmaniandevil** [comment]
Turns out orgTitle was being defined in the mappings but has never actually added to the index. Added and re-index and now I can search for california or New York

**Comment by Uafinder** [comment]
Great, it works finally 👍
