### ISSUE TITLE
Cant open folders and add images,  from using the photo block component

### ISSUE THREAD

**Issue by Anton69arb** [Kademi/kademi-dev#4803]
Hey, please would you be able to take a look and fix.
Cant open folders and add images, from using the photo block component.

![cant open folders and add images in a photo block component](https://user-images.githubusercontent.com/32444328/35071909-57463fd2-fc47-11e7-96f0-befb918aa80c.png)

http://kademi.admin.kademi.us/pages/kademi-dev/v7/getting-started/editing-content/
http://docs.kademi.co/getting-started/editing-content/editing-templates.html

**Comment by bradmac** [comment]
> self.mtree.addFile is not a function

**Comment by ducdhm** [comment]
Fixed!

**Comment by Anton69arb** [comment]
hey, the image is importing and folders are working, but they do not load into  the component once you select it and save, the image does not change, 

http://ant15.admin.kademi-ci.co/websites/onboarding-journey/version1/programs
http://ant15.admin.kademi-ci.co/websites/onboarding-journey/version1/programs/EK446/HN466/FL447

![1](https://user-images.githubusercontent.com/32444328/35129362-340dbcd2-fd20-11e7-968a-77ae13a49951.png)

**Comment by ducdhm** [comment]
@Anton69arb Can you give me more details?

**Comment by bradmac** [comment]
I just tried and i was able to select the image and have it display correctly:
![image](https://user-images.githubusercontent.com/826458/35560826-a40a1144-0602-11e8-9361-e8bb92c25141.png)

@Anton69arb is the bug still active?

**Comment by Anton69arb** [comment]
Its working now, could have been a lib update maybe
