### ISSUE TITLE
Assets on the keditor image uploading via text component bugs

### ISSUE THREAD

**Issue by Uafinder** [Kademi/kademi-dev#4881]
1. Assets list empty while uploading image via text component
- open page for edit
- add text component
- go to assets tab
- it will be empty

2. Upload image to the assets doesn't cause it appears in list
- open page for edit
- add text component
- go to assets tab
- click upload image
- upload it
- note that it's empty

![image](https://user-images.githubusercontent.com/1945230/35681501-39cbdc08-0766-11e8-9d08-e609ea9b065a.png)
![image](https://user-images.githubusercontent.com/1945230/35681506-3de93416-0766-11e8-9aae-07e2d1c8c08b.png)

http://vladtest28k.admin.kademi-ci.co/asset-manager/

**Comment by ducdhm** [comment]
@bradmac It's not frontend stuff. It's backend issue. When sending request to `/assets/?q=&type=`, server returns nothing. It worked but not for now.

**Comment by bradmac** [comment]
Fixed

**Comment by bradmac** [comment]
@ducdhm can you please confirm is working correctly?

**Comment by ducdhm** [comment]
Yes, it's working perfectly now

**Comment by Uafinder** [comment]
No it doesn't
![image](https://user-images.githubusercontent.com/1945230/35728533-8b571458-0814-11e8-822d-a1faab1fa4bf.png)
![image](https://user-images.githubusercontent.com/1945230/35728552-962396fe-0814-11e8-985c-e34427221b7f.png)

Both bugs is still there
Fresh account
http://vladtest28n.admin.kademi-ci.co/pages/vlad28nweb/version1/

**Comment by ducdhm** [comment]
@bradmac Can you help me check on QA?

**Comment by bradmac** [comment]
@ducdhm i've confirmed Vlad's problems
- I upload an image, and it is not shown or selected. I can search for it to find it, but users should not be required to search for the image they've just uploaded. After uploading, please ensure the image is selected 
- when i open the assets tab the list is initially empty. If i search i can then see assets, but the initial list should be shown without the user doing a search. This appears to be because the asset query returns no results, which I'll investigate

http://version1.vlad28nweb-vladtest28n.kademi-ci.co/assets/?q=&type=image

**Comment by bradmac** [comment]
After redeploying to CI is displaying initial asset list:
![image](https://user-images.githubusercontent.com/826458/35835381-42439510-0b3f-11e8-8a82-9d9aac6991d6.png)

**Comment by bradmac** [comment]
@ducdhm can you please ensure that when an item is uploaded it is selected and shown in the list.

Currently you're reloading the list with whatever search criteria was previously there (or none), and the image is only selected if its found in that list

This wont work. Eg i just searched for "abc" and uploaded an image called "red-dawn.png" and it wasnt in the reloaded list so it didnt get selected as the image to insert.

One option is to set the uploaded image file name as the search criteria.

**Comment by ducdhm** [comment]
Done!

**Comment by Uafinder** [comment]
Yup, it works!
