### ISSUE TITLE
Invoice isnt adding up

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#6323]
http://otm.admin.kademi.com.au/invoices/134514060/

![image](https://user-images.githubusercontent.com/826458/49052060-32989a00-f24f-11e8-9f44-3cbfc834f4c4.png)

**Comment by bradmac** [comment]
Should be

subtotal: 1940
tax: 194
total: 2134

**Comment by bradmac** [comment]
I made an edit, it saved, then i reloaded and now the subtotal and tax are correct

but the total should show tax+ subtotal

**Comment by bradmac** [comment]
OK, confirmed a few problems..
- when changing a row, the change is saved but the totals section isnt reloaded
- the totals section total doesnt include tax

**Comment by bradmac** [comment]
> the totals section total doesnt include tax

fixed

![image](https://user-images.githubusercontent.com/826458/49059914-0ccfbd00-f270-11e8-8e08-e19629acdd20.png)

**Comment by bradmac** [comment]
> when changing a row, the change is saved but the totals section isnt reloaded

@anhnt can you do this please

**Comment by Uafinder** [comment]
Ok, i'm seeing few problems
1. When you created a row, enter some data and then add next row, you could not change or fill Supplier column for previous row. It doesn't save
![image](https://user-images.githubusercontent.com/1945230/50339097-2d153380-051f-11e9-9006-1b48f3fb0542.png)
http://vladtest55q.admin.kademi-ci.co/invoices/18373916/

2. When you enter all values except tax - row will not save
![image](https://user-images.githubusercontent.com/1945230/50339147-55049700-051f-11e9-9fa7-58e8eee12500.png)
Refsresh
Row missed
![image](https://user-images.githubusercontent.com/1945230/50339173-60f05900-051f-11e9-80e7-7fcf55bc4bda.png)

**Comment by bradmac** [comment]
Fixed a couple of things, but there is a problem in js where the row is saved before the selected event for choosing the supplier.

**Comment by bradmac** [comment]
@anhnt can you look into this?

**Comment by anhnt** [comment]
Done, fixed several issues on purchased order, quote and invoice detail page

**Comment by Uafinder** [comment]
doh...
a bunch of new issues came
1. Supplier field is not enterable and searchable (no possible to type something to search there)
![image](https://user-images.githubusercontent.com/1945230/50535883-27d76a80-0b57-11e9-8e9d-c509aafbcb76.png)

2. When you enter row with some parameters it doubling it
![image](https://user-images.githubusercontent.com/1945230/50535895-50f7fb00-0b57-11e9-89f8-82a3c114804a.png)
http://vladtest55ss.admin.kademi-ci.co/invoices/18405832/

**Comment by anhnt** [comment]
Looks ok atm, please make sure you installed KPayment app and latest payment-lib

**Comment by Uafinder** [comment]
Both bugs still appears
Fresh account
http://vladtest56v.admin.kademi-ci.co/invoices/
https://drive.google.com/open?id=1dZ2tA7Msv0GAJjYF9wWnjLtow_Wcfkxt
