### ISSUE TITLE
Auctions app

### ISSUE THREAD

**Issue by bradmac** [Kademi/kademi-dev#69]
Create auctions
Edit auctions - types(highest bid, lowest unique bid)
Auctions on user dashboard
Auction page which allows bidding

**Comment by tuzzmaniandevil** [comment]
Auction App now created with Highest Bid and Lowest Unique bid,
Auction can be restricted to a group and/or organisation.
Auction can use Rewards points instead of money.
Auction allows bidding.

**Comment by bradmac** [comment]
@tuzzmaniandevil could please add docs into a auctions folder here:
http://admin.fuselms.olhub.com/repositories/kademi-dev/version1-fix-bug/ref/screens/theme/apps/#files-tab

**Comment by Uafinder** [comment]
1. When creating auction, system allows you to enter Upper case letters in title, but this should be restricted according to the message below.
2. When creating auction, validation messages on date field are absent. Instead we have next message when date fields are not filled in.
![image](https://cloud.githubusercontent.com/assets/1945230/5783345/aec0371a-9dca-11e4-96be-6c9325d0b60c.png)
3. When editing auction there is no validation on it's title which are present on creation. Is it ok?
4. Primary marks when uploading product images looks no in place. Is it ok?
![image](https://cloud.githubusercontent.com/assets/1945230/5783441/98ecb61a-9dcb-11e4-9aae-666d1747885b.png)
5. When uploading image of products cropping tool works only with square form, not free. Is it ok?
6. Preview button firstly causes an login screen, and then is gives next error page:
![image](https://cloud.githubusercontent.com/assets/1945230/5783503/406d638a-9dcc-11e4-8f1a-7296caa3c4e9.png)
7. When editing auction, notes field content does not saving at all. It becomes empty after you refresh page.
8. When editing auction, status field does not saving. It becomes DRAFT when you leave page and then open auction page again.
9. History tab contains only creating step. No editing steps there.

So, there is no possibility to see how it looks on the user side.

**Comment by Uafinder** [comment]
When you are enabling Auction App in Website options whole website gives you an 500 error message.
![image](https://cloud.githubusercontent.com/assets/1945230/5792560/fe8b27de-9f26-11e4-9568-1b3713e41583.png)

**Comment by Uafinder** [comment]
1. Looks like just need to fix help text about lower case inputs. They are allowed, but help text says that they are not.
2. Creation bugs:
![image](https://cloud.githubusercontent.com/assets/1945230/5807010/74d5ad96-a027-11e4-94e7-94c2556f7af7.png)
![image](https://cloud.githubusercontent.com/assets/1945230/5807036/c7bf6f10-a027-11e4-9bfe-fbbb81a933d7.png)
3. Still active
4. Still active
5. Still active
6. Error page gone because of auction app was not enabled. BUT. Preview button firstly causes an login screen!  Shouldn't be!
7. Still active
8. Still active
9. Still active
10. Still active.
11. 500 error is fixed.

**Comment by tuzzmaniandevil** [comment]
"4. Primary marks when uploading product images looks no in place. Is it ok? " - Fixed

**Comment by tuzzmaniandevil** [comment]
"1. Looks like just need to fix help text about lower case inputs. They are allowed, but help text says that they are not." - Help text changed.

**Comment by tuzzmaniandevil** [comment]
"2. When creating auction, validation messages on date field are absent. Instead we have next message when date fields are not filled in. " - Fixed
"2. Creation bugs: " - You can't select an end date that is before the start date.

**Comment by tuzzmaniandevil** [comment]
"3. When editing auction there is no validation on it's title which are present on creation. Is it ok?" - fixed

**Comment by tuzzmaniandevil** [comment]
"5. When uploading image of products cropping tool works only with square form, not free. Is it ok?" - Fixed

**Comment by tuzzmaniandevil** [comment]
"6. Preview button firstly causes an login screen, and then is gives next error page: " - Fixed

**Comment by tuzzmaniandevil** [comment]
"7. When editing auction, notes field content does not saving at all. It becomes empty after you refresh page." - Fixed

**Comment by tuzzmaniandevil** [comment]
"8. When editing auction, status field does not saving. It becomes DRAFT when you leave page and then open auction page again." - Fixed

**Comment by tuzzmaniandevil** [comment]
"9. History tab contains only creating step. No editing steps there." - This is correct, the history tab only shows when the auction was created, each bid placed and when the auction closes and the winning bidder.

**Comment by tuzzmaniandevil** [comment]
"10. When editing auction, looks like some help text is duplicated. " - Fixed

**Comment by Uafinder** [comment]
1. Checked. Ok
2. Partially fixed. Bug about mouse cursor as crossed circle when you bring it to date fields still active!
3. Checked. Ok
4. Checked. Ok
5. Checked. Ok
6. Checked. Ok
7. Nope. Still active!
8. Checked. Ok
9. Understood
10. Checked. Ok

**Comment by tuzzmaniandevil** [comment]
"2. Partially fixed. Bug about mouse cursor as crossed circle when you bring it to date fields still active!" - Fixed

**Comment by Uafinder** [comment]
1. Auction Image on the front-end site is re-sized. Looks not very pretty.
![image](https://cloud.githubusercontent.com/assets/1945230/6007917/5fc7d636-ab26-11e4-8d84-0e1755569689.png)
And BTW: it shows end time of auction as "3 days from now". Is this correct?
2. IE shows bid amount as simple count (like 50), without digits after the comma (like 50,00).
![image](https://cloud.githubusercontent.com/assets/1945230/6008085/83f2df0a-ab27-11e4-9333-0eb336111d82.png)
3. When you a bid, it doesn't show in Bid History while are not refresh the page.
4. Bid history shows only last five bids (front-end and admin console). Well, i can understand this in front-end (i think this is incorrect), but admin should have a full bid history for sure.
![image](https://cloud.githubusercontent.com/assets/1945230/6008169/29ec873a-ab28-11e4-9b25-e3bfa075e097.png)
5. Is it should show a minimum bid amount for the user? Or user should guess what the minimal bid is?
![image](https://cloud.githubusercontent.com/assets/1945230/6008230/9c8c1e9a-ab28-11e4-9291-4385bad3e589.png)

**Comment by tuzzmaniandevil** [comment]
"7. Nope. Still active!" - Fixed

**Comment by Uafinder** [comment]
6. Start date has no influence to the auction work. I've set a start date to the a few days later and have been able to see an auction and to place a bid. Should be fixed.
7. Looks like it takes a timestamp from different places - i've setup that auction should expire now (22:16 my time), but timestapt tells me that it expired 11 hours ago. Should be checked and fixed.
![image](https://cloud.githubusercontent.com/assets/1945230/6008446/38b8eaa4-ab2a-11e4-9767-13cfd80e551d.png)

**Comment by tuzzmaniandevil** [comment]
"Bid history shows only last five bids (front-end and admin console). Well, i can understand this in front-end (i think this is incorrect), but admin should have a full bid history for sure. " - Fixed

**Comment by tuzzmaniandevil** [comment]
"Is it should show a minimum bid amount for the user? Or user should guess what the minimal bid is? " - Fixed, If there is no bids placed it will display starting value.

**Comment by tuzzmaniandevil** [comment]
"6.Start date has no influence to the auction work. I've set a start date to the a few days later and have been able to see an auction and to place a bid. Should be fixed." - Fixed, Doesn't allow you to place a bid if it's before the start date.

**Comment by tuzzmaniandevil** [comment]
"1. Auction Image on the front-end site is re-sized. Looks not very pretty. " - Moved to seperate Issue https://github.com/Kademi/kademi-dev/issues/134

**Comment by tuzzmaniandevil** [comment]
"3. When you a bid, it doesn't show in Bid History while are not refresh the page." - @Uafinder is this when using IE?

**Comment by tuzzmaniandevil** [comment]
"7.Looks like it takes a timestamp from different places - i've setup that auction should expire now (22:16 my time), but timestapt tells me that it expired 11 hours ago. Should be checked and fixed." - The timestamp defaults to NZDT if no time zone is set in the organisation, check the time zone in the organisation and change to your local time zone and retest.

**Comment by Uafinder** [comment]
"2. Partially fixed. Bug about mouse cursor as crossed circle when you bring it to date fields still active!" - Fixed - YES. OK!
7. NOTES IS OK!
1. Understood
7. Understood.

**Comment by Uafinder** [comment]
6.Start date has no influence to the auction work. I've set a start date to the a few days later  and have been able to see an auction and to place a bid. Should be fixed." - Fixed, Doesn't allow you to place a bid if it's before the start date.
I still can to place a bid to an auction which are not yet started.
![image](https://cloud.githubusercontent.com/assets/1945230/6048729/1768c814-acbb-11e4-8e06-38f933aa6818.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6048738/247dfda8-acbb-11e4-9959-c54eda36b0fa.png)

New ones:
1. When uploading image to an auction image doesn't appears without refreshing a page. Should be fixed.
2. There is no possibility choose a default image for an auction. They all have the "default" mark. The last uploaded image is showing for user in the front-end.
![image](https://cloud.githubusercontent.com/assets/1945230/6048813/c9eafe6c-acbb-11e4-961b-5d084d81545f.png)
3. I've setup a timezone for my org but something wrong with time.Look here.
Timezone is setup to Europe/Kiev. My local time is 22:20 now. I've create an auction which are available from now.
![image](https://cloud.githubusercontent.com/assets/1945230/6048884/50357fd8-acbc-11e4-8632-f4979c731c0a.png)
But when i choose to edit auction it shows me another date and times.
![image](https://cloud.githubusercontent.com/assets/1945230/6048903/67a8e6f0-acbc-11e4-9fdb-99a355bc91da.png)
But, thats not all. I've setup auction to active and go to the frontpage. End time here is showing is my timezone and correct.
![image](https://cloud.githubusercontent.com/assets/1945230/6048942/a9f2c9ea-acbc-11e4-9bcd-cec23ef8967d.png)
I've place a bid and come back to admin console to watch this action on history panel. And here we saw the third, other date/time.
![image](https://cloud.githubusercontent.com/assets/1945230/6048999/e1aaab14-acbc-11e4-94e8-ee33dc7120a2.png)
Could you investigate?

**Comment by tuzzmaniandevil** [comment]
"There is no possibility choose a default image for an auction. They all have the "default" mark. The last uploaded image is showing for user in the front-end." - This is done when uploading an image, "Default" means the image can me any aspect ratio, it is the image "Default" aspect ratio.

**Comment by tuzzmaniandevil** [comment]
"1. When uploading image to an auction image doesn't appears without refreshing a page. Should be fixed." - Fixed

**Comment by tuzzmaniandevil** [comment]
"3. I've setup a timezone for my org but something wrong with time.Look here.
Timezone is setup to Europe/Kiev. My local time is 22:20 now. I've create an auction which are available from now." - Should be fixed now.

**Comment by tuzzmaniandevil** [comment]
"6.Start date has no influence to the auction work. I've set a start date to the a few days later and have been able to see an auction and to place a bid. Should be fixed." - Fixed, Doesn't allow you to place a bid if it's before the start date." - Fixed

**Comment by tuzzmaniandevil** [comment]
"I've place a bid and come back to admin console to watch this action on history panel. And here we saw the third, other date/time." - Fixed

**Comment by Uafinder** [comment]
"6.Start date has no influence to the auction work. I've set a start date to the a few days later and have been able to see an auction and to place a bid. Should be fixed." - Fixed, Doesn't allow you to place a bid if it's before the start date." - Fixed ----YES

"2. There is no possibility choose a default image for an auction. They all have the "default" mark. The last uploaded image is showing for user in the front-end." - This is done when uploading an image, "Default" means the image can me any aspect ratio, it is the image "Default" aspect ratio. ----- UNDERSTOOD

"1. When uploading image to an auction image doesn't appears without refreshing a page. Should be fixed." - Fixed _---- YES

**Comment by Uafinder** [comment]
"3. When you a bid, it doesn't show in Bid History while are not refresh the page." - @Uafinder is this when using IE?
No, it's happen everywhere. Prod.
![image](https://cloud.githubusercontent.com/assets/1945230/6134486/7a9d5cc0-b16a-11e4-8bb1-7765eb09081b.png)

- Auction images are not visible on the users dashboard
![image](https://cloud.githubusercontent.com/assets/1945230/6134586/23c20f6c-b16b-11e4-852f-cacc894881c5.png)

- time issue 1
It shows now correct relative time, but when you bring a cursor to it to see date/time it shows it in NZDT time zone no matter to previously setup  time zone for organisation.
![image](https://cloud.githubusercontent.com/assets/1945230/6134683/b4163282-b16b-11e4-9747-cbd22191ea7c.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6134728/1422fc8c-b16c-11e4-82c8-31c43034552f.png)

- time issue 2
![image](https://cloud.githubusercontent.com/assets/1945230/6134741/2e23fb90-b16c-11e4-9501-ba5a7b5d296d.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6134750/37ca3592-b16c-11e4-9664-6f3b46b4fa53.png)
There is a two hours difference between time in admin console and time in end-user interface here.

**Comment by tuzzmaniandevil** [comment]
""3. When you a bid, it doesn't show in Bid History while are not refresh the page." - @Uafinder is this when using IE?" - This won't work in prod as WebSockets currently don't work in prod, we are waiting for SSL.
